version: '3.8'

services:
  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: thuc
      DB_PASSWORD: thuc

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thuc
      MYSQL_DATABASE: db
      MYSQL_USER: thuc
      MYSQL_PASSWORD: thuc
    ports:
      - "3306:3306"
