version: '3.8'

services:
  web:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=php  

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php  
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
